version: '2'
services:
  db-mongodb:
    image: mongo:3.6
    volumes:
        - /mongodb:/data/db

  app-rabbit:
    image: rabbitmq:latest

  app-girder_worker:
    image: openchemistry/girder_worker:mdb
    build:
      context: ../../
      dockerfile: devops/docker/girder_worker/Dockerfile
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - DAC_OVERRIDE
      - SETUID
      - SETGID
      - NET_BIND_SERVICE
    links:
      - rabbit
      - girder
    environment:
      - GIRDER_WORKER_BROKER=amqp://guest:guest@rabbit/
      - GIRDER_WORKER_BACKEND=amqp://guest:guest@rabbit/
    depends_on:
      - rabbit

  app-girder:
    image: openchemistry/girder:mdb
    build:
      context: ../../
      dockerfile: devops/docker/girder/Dockerfile
    command: -d mongodb://mongodb:27017/girder
    ports:
          - 8081:8080
    volumes:
      - app-localassetstore.mdb:/assetstore
      - app-curatedassetstore.mdb:/curatedassetstore
    links:
      - mongodb
      - rabbit
    environment:
      - GIRDER_WORKER_BROKER=amqp://guest:guest@rabbit/
      - GIRDER_WORKER_BACKEND=amqp://guest:guest@rabbit/
    depends_on:
      - mongodb

  web-nginx:
    image: openchemistry/nginx:mdb
    build:
      context: ../../
      dockerfile: devops/docker/nginx/Dockerfile
    ports:
      - 6000:80
    volumes:
      - web-certs.ssl-testing:/etc/letsencrypt
      - web-certbot-webroot.ssl-testing:/data/letsencrypt
    links:
      - girder
    depends_on:
      - girder

volumes:
  app-localassetstore.mdb:
    db-mongodb.mdb:
    external: true
    driver: rancher-nfs
  app-curatedassetstore.mdb:
    db-mongodb.mdb:
    external: true
    driver: rancher-nfs
  db-mongodb.mdb:
    external: true
    driver: rancher-nfs

